version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Str0ngP@ss!2023"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__SqlServerDbConnection: "server=db;Database=ReadingIsGoodDb;User Id=sa;Password=Str0ngP@ss!2023;TrustServerCertificate=true;"
